image: maven:3-jdk-8

stages:
  - before
  - compile
  - test
  - build

before:
  stage: before
  script:
  - "mvn install:install-file -Dfile=lib/parser-1.22.jar"
  - "mvn install:install-file -Dfile=lib/automaton-1.8.jar"
  - "mvn install:install-file -Dfile=lib/XMLCollections-1.12.jar"
  - "mvn install:install-file -Dfile=lib/offlineJRAW-1.1.0.jar"
  
compile:
  stage: compile
  script: "mvn clean compile"

test:
  stage: test
  script: 
  - "mvn test"
  - "cat target/site/jacoco/index.html"

build:
  stage: build
  script: "mvn package shade:shade"
